[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"], optional = true }
common = { path = "../common" }
async-trait = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
connect = ["async-trait", "tokio"]
default = ["connect"]