[package]
name = "home-server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
common = { path = "../common" }

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
